# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('dateOfUploading', models.DateField()),
                ('personalAccount', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=10)),
                ('housing', models.CharField(max_length=10)),
                ('flat', models.CharField(max_length=10)),
                ('numberOfResidents', models.CharField(max_length=10)),
                ('currentReportingPeriod', models.DateField()),
                ('chargedForGasInCurrentPeriod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargedForStateDutyInTheCurrentPeriod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargedForChangingGasSupplyRegimesInTheCurrentPeriod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAtTheEndOfTheReportingPeriodForGas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAtTheEndOfTheReportingPeriodForStateDuty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAtTheEndOfTheReportingPeriodForChangingGasSupplyRegimes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('symptomOfHavingAnIndividualCounter', models.IntegerField()),
                ('currentMeterReading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('balanceAtTheBeginningOfThePeriodGasSupply', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAtTheBeginningOfThePeriodChangeInGasSupplyRegimes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAtTheBeginningOfThePeriodOfStateDuty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
