# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrymodel',
            name='currentReportingPeriod',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='dateOfUploading',
            field=models.CharField(max_length=30),
        ),
    ]
