# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0002_auto_20170707_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheBeginningOfThePeriodChangeInGasSupplyRegimes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheBeginningOfThePeriodGasSupply',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheBeginningOfThePeriodOfStateDuty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForChangingGasSupplyRegimes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForGas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForStateDuty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='chargedForChangingGasSupplyRegimesInTheCurrentPeriod',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='chargedForGasInCurrentPeriod',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='chargedForStateDutyInTheCurrentPeriod',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='currentMeterReading',
            field=models.CharField(max_length=50),
        ),
    ]
