# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0003_auto_20170707_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheBeginningOfThePeriodChangeInGasSupplyRegimes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheBeginningOfThePeriodGasSupply',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheBeginningOfThePeriodOfStateDuty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForChangingGasSupplyRegimes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForGas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForStateDuty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='chargedForChangingGasSupplyRegimesInTheCurrentPeriod',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='chargedForGasInCurrentPeriod',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='chargedForStateDutyInTheCurrentPeriod',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='currentMeterReading',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='currentReportingPeriod',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='flat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='home',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='housing',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='locality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='numberOfResidents',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
