# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0004_auto_20170708_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrymodel',
            name='balanceAtTheEndOfTheReportingPeriodForGas_new',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registrymodel',
            name='currentMeterReading_new',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
